name: CI
on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  CI:
    name: Linting and Style Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install
      run: npm install
    - name: ESLint
      run: npx eslint ./src/**/*.ts --max-warnings=0
    - name: TypeScript
      run: tsc --noEmit              
    - name: Prettier Check
      uses: rutajdash/prettier-cli-action@v1.0.2
      with:
        file_pattern: './src/**/*.ts'
        config_path: './.prettierrc'
        fail_on_error: true
            